### ISSUE TITLE
Broken "Run OKD in a Container" link on source/index.html.erb

### ISSUE THREAD

**Issue by nhojpatrick** [openshift-cs/okd.io#100]
This file `https://github.com/openshift-cs/okd.io/blob/master/source/index.html.erb`

This url `https://docs.okd.io/latest/getting_started/administrators.html#running-in-a-docker-container`

Give 404 page.

I've tried searching for the what the correct link should be but not sure what to put in pr for "Run OKD in a Container"

**Comment by wgordon17** [comment]
@dmueller2001 It looks like that OKD docs have been updated to point to OKD v4. Could you please review our site content and update as necessary for OKD v4?

**Comment by dmueller2001** [comment]
https://docs.okd.io/3.11/getting_started/administrators.html#running-in-a-docker-container is the correct link, I'll update it 
please not that the latest docs are 4.x related and some of this content will be revised shortly to reflect that

**Comment by dmueller2001** [comment]
done
