### ISSUE TITLE
Modifications required for ensuring use of inclusive language

### ISSUE THREAD

**Issue by binnes** [openshift-cs/okd.io#203]
As part of the RedHat support of the [inclusinve naming](https://inclusivenaming.org) initiative.  We want to ensure okd.io doesn't contain any inappropriate language.

A scan using the [conscious language checker](https://github.com/Humbedooh/clc) raised the following issues

- The primary branch needs to be renamed from master to main.  There are a number of things that will need to be coordinated with this change.
    - there are many links within the content pointing back to the git repo of the form ```<a href="https://github.com/openshift/origin/tree/master/ ...``` 
    - there is content that directly specifies the master branch (such as CONTRIBUTING.md).  
    - there may be some external tools that use the master branch to publish the web site which will also need updating to use the main branch
    - anyone with a clone of the repo should update their clone configuration to use the main branch
       ```shell
        git branch -m master main
        git fetch origin
        git branch -u origin/main main
        git remote set-head origin -a
        ```
- Some files use master to indicate the primary, such as /source/css/_variables_scss.  These should be changed to more appropriate words, such as ```primary``` or ```main```.  Search and replace is needed across the entire repo.
- /source/.htaccess has 2 comments which use ```whitelist```.  These comments should be modified to use ```allow``` or ```allowlist```
- There is a typo in file /source/js/slide/camera.js, line 32 where the **t** is missing of the work **the**, so flags as **he**
- /source/js/twitter/jquery.tweet.js uses **his** and should be changed to **their**

The other thing which is reported is file /source/js/rs-plugin/js/jquery.themepunch.revolution.js, which uses **masterspeed** as a variable name to control the speed for the slide transition.  Does this need to be changed as it looks like an imported package?

**Comment by wgordon17** [comment]
@jiri-fiala Are you able to review this?

**Comment by binnes** [comment]
Investigate to see if this can be automated as part of the github actions run on commit (once beta moves to live)

**Comment by binnes** [comment]
Scan returns 66 cases of word master being included in the repository.  These are due to:

- github.com/openshift/library repo main branch is called master
- github.com/openshift/community repo main branch is called master
- github.com/openshift/okd repo main branch is called master
- openshift control plans nodes are called master nodes

**Comment by binnes** [comment]
@dmueller2001 please confirm you are happy for us to close this with the 66 instances of master

**Comment by brianinnes** [comment]
open issues with community repos to request they change
