### ISSUE TITLE
Switch MkDocs site live

### ISSUE THREAD

**Issue by binnes** [openshift-cs/okd.io#223]
This PR is to track the work needed to switch from the Middleman implementation to the MkDocs implementation in the beta branch

Tasks to be completed:

- [x] remove web hooks for existing site building process
- [x] rename master branch to main
- [x] tag the main branch as the last middleman version
- [x] deliver the beta branch into main
- [x] alter the repo configuration to run the automation on changes to main branch rather than beta branch
- [x] alter the MkDocs configuration to reference the main branch rather than beta (this change should test the automation on the main branch)
- [x] add the CNAME to the git repo for serving GitHub pages as okd.io (see [github docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)) for details
- [x] alter DNS for okd.io to point to GitHub pages site
    - Note: check home page works without needing to specify index.html.  Using okd.io is not ideal as the repo name, as it becomes part of the URL of the GitHub pages URL and browsers think okd.io is a document rather than a directory
- [x] tidy up the Red Hat pipeline used to build the Middleman site
- [x] close beta branch
- [x] tidy up issues and PR that refer to Middleman implementation
- [x] tidy up any branches no longer needed

**Comment by jiri-fiala** [comment]
I've set the `okd.io` domain for the Pages per the docs (which created [this commit](https://github.com/openshift-cs/okd.io/commit/f75152f849801a0e24ccf23a4ac3f1502f50fa79)) and marked that task as done above, @wgordon17 is going to update the DNS.

I have also disabled [the existing web hook](https://github.com/openshift-cs/okd.io/settings/hooks/127653484), so no site builds will be triggered on pushing into the current `master` branch.

**Comment by binnes** [comment]
Site now live
