### ISSUE TITLE
Missing security contacts on okd.io

### ISSUE THREAD

**Issue by sandrobonazzola** [openshift-cs/okd.io#236]
On the website there are no instructions on how to report security issues for OKD.

```
$ git describe 
middleman-11-g3036884

$ grin -i security
./about.md:
   43 : ## What sorts of security controls does OpenShift provide for containers?
   45 : OKD runs with the following security policy by default:
   54 : - Regular users and project admins cannot change their security quotas.
   69 : See the [security documentation](https://docs.okd.io/latest/authentication/managing-security-context-constraints.html){: target=_blank} more on confining applications.
./guides/aws-ipi.md:
   30 : - 10 distinct security groups
./guides/azure-ipi.md:
   29 : - 2 network security groups
./index.md:
   26 : OKD embeds Kubernetes and extends it with security and other integrated concepts
```

As an example, for oVirt project we have: https://www.ovirt.org/community/security.html

**Comment by brianinnes** [comment]
suggest using the general link : https://github.com/coreos/ignition/security/policy.  Discuss at documentation working group

**Comment by travier** [comment]
https://github.com/coreos/.github > "Source" for the policy

**Comment by elmiko** [comment]
we talked about this a little at the community devel meeting today, i think it would be cool if we could establish a process for taking security bugs/reports in the okd community. then we could triage the issues and make sure that bugs get opened in the proper projects (eg FCOS, OpenShift, Kubernetes, etc).

**Comment by binnes** [comment]
closed as moved to project board [https://github.com/openshift-cs/okd.io/issues/236](https://github.com/openshift-cs/okd.io/issues/236)
