### ISSUE TITLE
okd.io community section misses details included in https://github.com/openshift/community/

### ISSUE THREAD

**Issue by sandrobonazzola** [openshift-cs/okd.io#255]
When looking at community section in https://www.okd.io/community/ it delegates the references to the organization of the community to an external site https://github.com/openshift/community/blob/master/CHARTER.md .
It would make sense to me to consolidate the community related information to a single place.
Would make sense to me using a git submodule importing from https://github.com/openshift/community/ if needed, but would be nice to get the stuff included in the charter displayed on the website and indexed my search engines.

**Comment by binnes** [comment]
fixed in #265
