### ISSUE TITLE
Document new main chat avenue as #okd:fedoraproject.org (Matrix)

### ISSUE THREAD

**Issue by Conan-Kudo** [openshift-cs/okd.io#256]
Per our discussion in the WG, we're relocating our primary chat to [`#okd:fedoraproject.org`](https://matrix.to/#/#okd:fedoraproject.org). The room is now set up and now we need to document this in the website to start directing people there.

**Comment by binnes** [comment]
Moved to a discussion about communication channels, as this channel doesn't appear to have been adopted : https://github.com/openshift/okd/discussions/1207
