### ISSUE TITLE
Update vsphere install guide for 4.9

### ISSUE THREAD

**Issue by daxelrod-datto** [openshift-cs/okd.io#259]
Please update the guides for installing OKD on vsphere for any changes that may have occurred in 4.9:

- https://github.com/openshift-cs/okd.io/blob/main/docs/guides/vsphere-prereqs.md
- https://github.com/openshift-cs/okd.io/blob/main/docs/guides/automated-vsphere-upi.md
- https://github.com/openshift-cs/okd.io/blob/main/docs/guides/vsphere-ipi.md

I'm unable to set assignees, but this should be assigned to @JaimeMagiera , who has volunteered to do this.

Thank you!

**Comment by binnes** [comment]
There needs to be some more context added to these issues. We need to ensure they add value, not just repeat what is in the product documentation. There should also be some consistency between the different underlying platforms. Suggest we gather the people together and set some key points and some general content guidelines for these guides. This could be part of the docs bi-weekly meeting?

**Comment by daxelrod-datto** [comment]
Thanks for calling that out @binnes ! Closing this until we have a better idea of what exactly we want to do with these guides. Please see the discussion in https://github.com/openshift-cs/okd.io/discussions/262 .
