### ISSUE TITLE
OKD 4.1

### ISSUE THREAD

**Issue by jamescassell** [openshift-cs/okd.io#80]
Looks like OKD 4.1.0 was released on May 1, but okd.io makes no mention of how to install it: https://github.com/openshift/origin/releases/tag/v4.1.0

**Comment by smarterclayton** [comment]
Hi, at this point in time we don't have an OKD release.  That's a tag in the origin repo for code that corresponds to the internal development versions, but we don't have the actual binaries that would correspond to it that also include Fedora CoreOS (or an alternative).  That's still coming, hopefully after we reach consensus on the deliverable goal.  Please see the mailing lists for up to date discussion.
