### ISSUE TITLE
okd end user community section is not updating properly

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/okd.io#81]
Currently only showing 490 as # of community members.. it's 500+ 

<img width="989" alt="Screen Shot 2019-06-17 at 2 48 24 PM" src="https://user-images.githubusercontent.com/4029488/59639074-fb1c0d00-910e-11e9-9a1b-ec955ae607ac.png">

**Comment by jiri-fiala** [comment]
@dmueller2001, the list is pulled from commons on okd.io build, which is not so frequent. I've triggered the build manually and the updated list is deployed now.
