### ISSUE TITLE
OKD version still defined as being linked to k8s versions

### ISSUE THREAD

**Issue by wgordon17** [openshift-cs/okd.io#95]
The https://www.okd.io/#v3 section "What is OKD", specifies that 

> An OKD release corresponds to the Kubernetes distribution

While this is true for 3.x releases, this is no longer true for 4.x releases. We should add some text here to provide further context.

Reference: https://github.com/openshift/openshift-docs/issues/13602

**Comment by wgordon17** [comment]
@jeffb4 FYI

**Comment by baberlevi** [comment]
I find the wording confusing for the 3.x releases as well since okd 3.11 corresponds to k8s 1.11, and the text explicitly calls out major.minor as matching , e.g. 

> for example, OKD 1.10 includes Kubernetes 1.10

**Comment by wgordon17** [comment]
@baberlevi Technically, ODK versions match the K8s versions. ODK 1.11 == K8s 1.11. It's the OCP versioning (downstream, enterprise version) that uses the 3.x versioning.

However, the 4.x versioning does diverge from this "one to one" type matching where you can determine the K8s version just by looking at the OKD versioning.

**Comment by baberlevi** [comment]
Maybe I'm missing it, but all the OKD version numbers I see seem to match OCP, e.g.
https://docs.okd.io/3.11/welcome/index.html
this says 3.11, not 1.11

**Comment by wgordon17** [comment]
@baberlevi 🤦‍♂ You're absolutely right. I'm sorry, I just confirmed internally...it was my own misconception (probably perpetuated by this very page) that led me to think OKD and OCP versions differed.

I will ensure this gets addressed as well.

**Comment by dmueller2001** [comment]
"The current alpha OKD 4 release corresponds to the Kubernetes distribution 1.16; the Beta release will correspond to Kubernetes distribution 1.17" is the new text to be added by @dmueller2001

**Comment by wgordon17** [comment]
Closed by #96
