### ISSUE TITLE
update coreos logo to fedora coreos (svg)

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/okd.io#98]
still need to find an svg version of this https://getfedora.org/static/images/fedora-coreos-logo.png @dustymabe

**Comment by dustymabe** [comment]
Sent you a few in emails.. Can you confirm you got them?

**Comment by jomeier** [comment]
I added a png version. Send me the svg and I will replace it with that, please.

**Comment by jomeier** [comment]
Closed.

**Comment by dustymabe** [comment]
Sent the SVGs to you in an email @jomeier!
